{"name": "test_login[caseinfo0]", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'new_value' referenced before assignment", "trace": "self = <testcases.test_login.test_login.TestAPI object at 0x0000021AC1E76260>\ncaseinfo = {'extract': {'access_token': '\"access_token\":\"(.*?)\"', 'username': '$.data.userInfo.username'}, 'name': '使用正确的账号密码登录',...62o/Uc=', 'type': 0, 'userName': 'chenjiawei132785'}, 'method': 'post', 'url': '/micro/ent/login'}, 'title': '登录', ...}\nbase_url = 'http://wanjidev.wandianzhang.com'\n\n    @pytest.mark.parametrize(\"caseinfo\", read_testcase_yaml(concurrent_path + \"\\\\test_login.yaml\"))\n    def test_login(self, caseinfo, base_url):\n>       RequestUtil().standard_yaml_case(caseinfo, base_url)\n\ntest_login.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\commons\\request_util.py:23: in standard_yaml_case\n    self.replace_hotload(yaml_str)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <commons.request_util.RequestUtil object at 0x0000021AC1E762F0>\nyaml_str = 'extract:\\n  access_token: \\'\"access_token\":\"(.*?)\"\\'\\n  username: $.data.userInfo.username\\nname: \"\\\\u4F7F\\\\u7528\\\\u6...Name: chenjiawei132785\\n  method: post\\n  url: /micro/ent/login\\ntitle: \"\\\\u767B\\\\u5F55\"\\nvalidate: \"\\\\u65AD\\\\u8A00\"\\n'\n\n    def replace_hotload(self, yaml_str):\n        regexp = \"\\\\$\\\\{(.*?)\\\\((.*?)\\\\)}\"\n        # print(yaml_str)\n        fun_list = re.findall(regexp, yaml_str)\n        print(\"fun_list:%s\" % fun_list)\n        for f in fun_list:\n            # 如果他的参数不等于他的字符串代表有参数 ，否则\n            if f[1] != \"\":\n                print(\"有参数\")\n                new_value = getattr(DebugTalk(), f[0])()\n            else:\n                print(\"没有参数\")\n                new_value = getattr(DebugTalk(), f[1])()\n>       print(new_value)\nE       UnboundLocalError: local variable 'new_value' referenced before assignment\n\n..\\..\\commons\\request_util.py:103: UnboundLocalError"}, "start": 1672881806210, "stop": 1672881806211, "uuid": "d909e6e0-3e1c-470d-90e7-51226baa56ef", "historyId": "bed45d5f6f613b15f75e9c6cbb7a36ad", "testCaseId": "60173ae71bf409aa79e3df914c3ae944", "fullName": "testcases.test_login.test_login.TestAPI#test_login", "labels": [{"name": "epic", "value": "万集接口自动化测试"}, {"name": "parentSuite", "value": "testcases.test_login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "host", "value": "DESKTOP-5ALEO36"}, {"name": "thread", "value": "14076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login.test_login"}]}